replicaCount: 2

image:
  repository: 471112851559.dkr.ecr.us-west-2.amazonaws.com/django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70