apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_DB: "{{ .Values.config.POSTGRES_DB }}"
  POSTGRES_USER: "{{ .Values.config.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.config.POSTGRES_PASSWORD }}"
  POSTGRES_HOST: "{{ .Values.config.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ .Values.config.POSTGRES_PORT }}"